### ISSUE TITLE
Question: Implementing Bluetooth Low Energy Transport

### ISSUE THREAD

**Issue by bgiori** [stuffrabbit/SwiftCoAP#12]
Hi, I'm looking for a CoAP library for iOS which can handle non-IP transports, in this case Bluetooth Low Energy (BLE).

My question is, If I were to write a custom SCCoAPTransportLayerProtocol for BLE using a CBPeripheral's address 128bit UUID as the address with port 0, would any of the source need to be modified? That is, can the SwiftCoAP handle non-IP addresses?

Another option would be to map the CBPeripheral's address to an IP address to use with SwiftCoAP if necessary.

Let me know what you think.

Thanks,
Brian

**Comment by stuffrabbit** [comment]
Hey Brian,
really interesting topic! 

My intention in implementing the `SCCoAPTransportLayerProtocol ` was to provide an api to entirely abstract from the way the data is transported. I myself used it to send CoAP messages from an iPhone to an Apple Watch via the given Bluetooth connectivity frameworks from Apple.

So yes, if everything works as it is supposed be changing the source of SwiftCoAP should not be necessary. All you need to do is to provide your own transport layer in order to send and receive data and to handle your non-IP addresses.

If you need examples or anything else, just contact me.

Best regards,

Wojtek

**Comment by bgiori** [comment]
Hi Wojtek,
First I'd like to say thanks for open sourcing this project! 

After implementing my BLE transport layer protocol and encountering odd responses, I realized that the peripheral I'm communicating with expects the [coap+tcp](https://tools.ietf.org/html/draft-ietf-core-coap-tcp-tls-09) packet format. 

At a glance, this format removes the version and message type from the CoAP header; however, it seems a full coap+tcp implementation would require quite a bit more than removing a few bytes from the header. Have you implemented this before? If not I can give a whack at a naive implementation for BLE.
